# Generated by Django 4.2.18 on 2025-07-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên blog')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('rss_url', models.URLField(verbose_name='RSS URL')),
                ('homepage_url', models.URLField(blank=True, verbose_name='Trang chủ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True, verbose_name='Lần crawl cuối')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
            ],
            options={
                'verbose_name': 'Nguồn Blog',
                'verbose_name_plural': 'Nguồn Blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('link', models.URLField(unique=True, verbose_name='Link gốc')),
                ('excerpt', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Ảnh thumbnail')),
                ('published_date', models.DateTimeField(verbose_name='Ngày đăng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='aggregator.blogsource', verbose_name='Nguồn blog')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_date'],
            },
        ),
    ]
