# Generated by Django 4.2.18 on 2025-07-27 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Màu sắc')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogsource',
            options={'ordering': ['name'], 'verbose_name': 'Nguồn Blog', 'verbose_name_plural': 'Nguồn Blog'},
        ),
        migrations.AddField(
            model_name='blogsource',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tác giả'),
        ),
        migrations.AddField(
            model_name='blogsource',
            name='language',
            field=models.CharField(default='vi', max_length=10, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='blogsource',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tags (phân cách bằng dấu phẩy)'),
        ),
        migrations.CreateModel(
            name='MyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Mô tả ngắn')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Ảnh thumbnail')),
                ('is_published', models.BooleanField(default=False, verbose_name='Đã xuất bản')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (phân cách bằng dấu phẩy)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_posts', to='aggregator.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết của tôi',
                'verbose_name_plural': 'Bài viết của tôi',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='aggregator.category', verbose_name='Danh mục'),
        ),
    ]
